# Generated by Django 4.2.16 on 2025-11-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='امیررضا کریمی', max_length=100)),
                ('title', models.CharField(default='توسعه\u200cدهنده فول\u200cاستک', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('bio', models.TextField(default='متخصص در طراحی و توسعه وب\u200cسایت\u200cهای مدرن...')),
                ('location', models.CharField(default='تهران، ایران', max_length=100)),
                ('email', models.EmailField(default='amir@example.com', max_length=254)),
                ('phone', models.CharField(default='۰۹۱۲۳۴۵۶۷۸۹', max_length=15)),
                ('github', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('tech1', models.CharField(blank=True, max_length=50)),
                ('tech2', models.CharField(blank=True, max_length=50)),
                ('link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('percentage', models.IntegerField(default=80)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
